import type { Lead, Project, User, Contact, Company, FollowUp, Enquiry } from '../types';

export const sampleUsers: User[] = [
  { id: 'u1', name: 'Admin', email: 'admin@deepika.com', role: 'Admin', status: 'Active' },
];

export const sampleCompanies: Company[] = [];

export const sampleContacts: Contact[] = [
  {
    "id": "con-fb-1",
    "fullName": "Ramya R",
    "designation": "Client / Enquirer",
    "phone": "FB Messenger",
    "isDecisionMaker": true,
    "type": "Client Active",
    "city": "Chennai / Tamil Nadu",
    "industry": "Construction / PEB",
    "createdAt": "2026-07-22T10:21:00.000Z"
  },
  {
    "id": "con-fb-2",
    "fullName": "Rajesh Madasamy",
    "designation": "Client / Enquirer",
    "phone": "FB Messenger",
    "isDecisionMaker": true,
    "type": "Client Active",
    "city": "Chennai / Tamil Nadu",
    "industry": "Construction / PEB",
    "createdAt": "2026-07-22T07:54:00.000Z"
  },
  {
    "id": "con-fb-3",
    "fullName": "Avj Architecture (Surya)",
    "designation": "Client / Enquirer",
    "phone": "FB Messenger",
    "isDecisionMaker": true,
    "type": "Client Active",
    "city": "Chennai / Tamil Nadu",
    "industry": "Construction / PEB",
    "createdAt": "2026-07-20T14:30:00.000Z"
  },
  {
    "id": "con-fb-4",
    "fullName": "Tyagi Nikhil",
    "designation": "Client / Enquirer",
    "phone": "FB Messenger",
    "isDecisionMaker": true,
    "type": "Client Active",
    "city": "Chennai / Tamil Nadu",
    "industry": "Construction / PEB",
    "createdAt": "2026-07-20T12:15:00.000Z"
  },
  {
    "id": "con-fb-5",
    "fullName": "Ravi Khede",
    "designation": "Client / Enquirer",
    "phone": "FB Messenger",
    "isDecisionMaker": true,
    "type": "Client Active",
    "city": "Chennai / Tamil Nadu",
    "industry": "Construction / PEB",
    "createdAt": "2026-07-20T11:00:00.000Z"
  },
  {
    "id": "con-fb-6",
    "fullName": "Raj Raj",
    "designation": "Client / Enquirer",
    "phone": "FB Messenger",
    "isDecisionMaker": true,
    "type": "Client Active",
    "city": "Chennai / Tamil Nadu",
    "industry": "Construction / PEB",
    "createdAt": "2026-07-17T18:20:00.000Z"
  },
  {
    "id": "con-fb-7",
    "fullName": "Barun Panigrahi",
    "designation": "Client / Enquirer",
    "phone": "FB Messenger",
    "isDecisionMaker": true,
    "type": "Client Active",
    "city": "Chennai / Tamil Nadu",
    "industry": "Construction / PEB",
    "createdAt": "2026-07-17T17:45:00.000Z"
  },
  {
    "id": "con-fb-8",
    "fullName": "Kishan Patel Kishan Patel",
    "designation": "Client / Enquirer",
    "phone": "FB Messenger",
    "isDecisionMaker": true,
    "type": "Client Active",
    "city": "Chennai / Tamil Nadu",
    "industry": "Construction / PEB",
    "createdAt": "2026-07-16T16:10:00.000Z"
  },
  {
    "id": "con-fb-9",
    "fullName": "Mugil",
    "designation": "Client / Enquirer",
    "phone": "FB Messenger",
    "isDecisionMaker": true,
    "type": "Client Active",
    "city": "Chennai / Tamil Nadu",
    "industry": "Construction / PEB",
    "createdAt": "2026-07-22T20:48:00.000Z"
  },
  {
    "id": "con-fb-10",
    "fullName": "Kartik Sethi",
    "designation": "Client / Enquirer",
    "phone": "FB Messenger",
    "isDecisionMaker": true,
    "type": "Client Active",
    "city": "Chennai / Tamil Nadu",
    "industry": "Construction / PEB",
    "createdAt": "2026-07-17T17:00:00.000Z"
  },
  {
    "id": "con-fb-11",
    "fullName": "Kathir Kaman",
    "designation": "Client / Enquirer",
    "phone": "FB Messenger",
    "isDecisionMaker": true,
    "type": "Client Active",
    "city": "Chennai / Tamil Nadu",
    "industry": "Construction / PEB",
    "createdAt": "2026-07-17T16:59:00.000Z"
  },
  {
    "id": "con-fb-12",
    "fullName": "Manna Foods",
    "designation": "Client / Enquirer",
    "phone": "FB Messenger",
    "isDecisionMaker": true,
    "type": "Client Active",
    "city": "Chennai / Tamil Nadu",
    "industry": "Construction / PEB",
    "createdAt": "2026-07-18T04:11:00.000Z"
  },
  {
    "id": "con-fb-13",
    "fullName": "M Rahman",
    "designation": "Client / Enquirer",
    "phone": "FB Messenger",
    "isDecisionMaker": true,
    "type": "Client Active",
    "city": "Chennai / Tamil Nadu",
    "industry": "Construction / PEB",
    "createdAt": "2026-07-11T17:42:00.000Z"
  },
  {
    "id": "con-fb-14",
    "fullName": "Nagallikar Manjunatha",
    "designation": "Client / Enquirer",
    "phone": "FB Messenger",
    "isDecisionMaker": true,
    "type": "Client Active",
    "city": "Chennai / Tamil Nadu",
    "industry": "Construction / PEB",
    "createdAt": "2026-07-11T15:34:00.000Z"
  }
];

export const sampleLeads: Lead[] = [
  {
    "id": "lead-fb-1",
    "contactName": "Ramya R",
    "companyName": "Ramya R Project",
    "phone": "FB Messenger",
    "projectType": "PEB Warehouse",
    "location": "Tamil Nadu, India",
    "landArea": "10,000 sq ft",
    "estimatedBudget": 25,
    "timeline": "Immediate",
    "source": "Facebook Messenger",
    "assignedTo": "u1",
    "status": "New",
    "leadScore": 80,
    "notes": "Captured from FB Messenger. Message: \"😍👑 STAR DESIGNER 👑😍😍 ...\"",
    "createdAt": "2026-07-22T10:21:00.000Z",
    "updatedAt": "2026-07-22T10:21:00.000Z"
  },
  {
    "id": "lead-fb-2",
    "contactName": "Rajesh Madasamy",
    "companyName": "Rajesh Madasamy Project",
    "phone": "FB Messenger",
    "projectType": "Cold Storage",
    "location": "Tamil Nadu, India",
    "landArea": "10,000 sq ft",
    "estimatedBudget": 30,
    "timeline": "Immediate",
    "source": "Facebook Messenger",
    "assignedTo": "u1",
    "status": "New",
    "leadScore": 80,
    "notes": "Captured from FB Messenger. Message: \"Hey 👋\"",
    "createdAt": "2026-07-22T07:54:00.000Z",
    "updatedAt": "2026-07-22T07:54:00.000Z"
  },
  {
    "id": "lead-fb-3",
    "contactName": "Avj Architecture (Surya)",
    "companyName": "Avj Architecture (Surya)",
    "phone": "FB Messenger",
    "projectType": "Mezzanine Floor",
    "location": "Tamil Nadu, India",
    "landArea": "10,000 sq ft",
    "estimatedBudget": 35,
    "timeline": "Immediate",
    "source": "Facebook Messenger",
    "assignedTo": "u1",
    "status": "New",
    "leadScore": 80,
    "notes": "Captured from FB Messenger. Message: \"Hi sir🏡 I am AVJ PLANNER Surya 😆 We offer architectural planning and structural design.\"",
    "createdAt": "2026-07-20T14:30:00.000Z",
    "updatedAt": "2026-07-20T14:30:00.000Z"
  },
  {
    "id": "lead-fb-4",
    "contactName": "Tyagi Nikhil",
    "companyName": "Tyagi Nikhil Project",
    "phone": "FB Messenger",
    "projectType": "Factory/Shed",
    "location": "Tamil Nadu, India",
    "landArea": "10,000 sq ft",
    "estimatedBudget": 40,
    "timeline": "Immediate",
    "source": "Facebook Messenger",
    "assignedTo": "u1",
    "status": "New",
    "leadScore": 80,
    "notes": "Captured from FB Messenger. Message: \"Hlo\"",
    "createdAt": "2026-07-20T12:15:00.000Z",
    "updatedAt": "2026-07-20T12:15:00.000Z"
  },
  {
    "id": "lead-fb-5",
    "contactName": "Ravi Khede",
    "companyName": "Ravi Khede Project",
    "phone": "FB Messenger",
    "projectType": "Civil Construction",
    "location": "Tamil Nadu, India",
    "landArea": "10,000 sq ft",
    "estimatedBudget": 45,
    "timeline": "Immediate",
    "source": "Facebook Messenger",
    "assignedTo": "u1",
    "status": "New",
    "leadScore": 80,
    "notes": "Captured from FB Messenger. Message: \"Hello\"",
    "createdAt": "2026-07-20T11:00:00.000Z",
    "updatedAt": "2026-07-20T11:00:00.000Z"
  },
  {
    "id": "lead-fb-6",
    "contactName": "Raj Raj",
    "companyName": "Raj Raj Project",
    "phone": "FB Messenger",
    "projectType": "Other",
    "location": "Tamil Nadu, India",
    "landArea": "10,000 sq ft",
    "estimatedBudget": 50,
    "timeline": "Immediate",
    "source": "Facebook Messenger",
    "assignedTo": "u1",
    "status": "New",
    "leadScore": 80,
    "notes": "Captured from FB Messenger. Message: \"Hi\"",
    "createdAt": "2026-07-17T18:20:00.000Z",
    "updatedAt": "2026-07-17T18:20:00.000Z"
  },
  {
    "id": "lead-fb-7",
    "contactName": "Barun Panigrahi",
    "companyName": "Barun Panigrahi Project",
    "phone": "FB Messenger",
    "projectType": "PEB Warehouse",
    "location": "Tamil Nadu, India",
    "landArea": "10,000 sq ft",
    "estimatedBudget": 55,
    "timeline": "Immediate",
    "source": "Facebook Messenger",
    "assignedTo": "u1",
    "status": "New",
    "leadScore": 80,
    "notes": "Captured from FB Messenger. Message: \"Messages and calls are secured with end-to-end encryption\"",
    "createdAt": "2026-07-17T17:45:00.000Z",
    "updatedAt": "2026-07-17T17:45:00.000Z"
  },
  {
    "id": "lead-fb-8",
    "contactName": "Kishan Patel Kishan Patel",
    "companyName": "Kishan Patel Kishan Patel Project",
    "phone": "FB Messenger",
    "projectType": "Cold Storage",
    "location": "Tamil Nadu, India",
    "landArea": "10,000 sq ft",
    "estimatedBudget": 60,
    "timeline": "Immediate",
    "source": "Facebook Messenger",
    "assignedTo": "u1",
    "status": "New",
    "leadScore": 80,
    "notes": "Captured from FB Messenger. Message: \"Messages and calls are secured with end-to-end encryption\"",
    "createdAt": "2026-07-16T16:10:00.000Z",
    "updatedAt": "2026-07-16T16:10:00.000Z"
  },
  {
    "id": "lead-fb-9",
    "contactName": "Mugil",
    "companyName": "Mugil Project",
    "phone": "FB Messenger",
    "projectType": "Mezzanine Floor",
    "location": "Tamil Nadu, India",
    "landArea": "10,000 sq ft",
    "estimatedBudget": 65,
    "timeline": "Immediate",
    "source": "Facebook Messenger",
    "assignedTo": "u1",
    "status": "New",
    "leadScore": 80,
    "notes": "Captured from FB Messenger. Message: \"Hi - Interested in Pre-Engineered Building options\"",
    "createdAt": "2026-07-22T20:48:00.000Z",
    "updatedAt": "2026-07-22T20:48:00.000Z"
  },
  {
    "id": "lead-fb-10",
    "contactName": "Kartik Sethi",
    "companyName": "Kartik Sethi Project",
    "phone": "FB Messenger",
    "projectType": "Factory/Shed",
    "location": "Tamil Nadu, India",
    "landArea": "10,000 sq ft",
    "estimatedBudget": 70,
    "timeline": "Immediate",
    "source": "Facebook Messenger",
    "assignedTo": "u1",
    "status": "New",
    "leadScore": 80,
    "notes": "Captured from FB Messenger. Message: \"Hello - Call is not connecting please contact this number sir\"",
    "createdAt": "2026-07-17T17:00:00.000Z",
    "updatedAt": "2026-07-17T17:00:00.000Z"
  },
  {
    "id": "lead-fb-11",
    "contactName": "Kathir Kaman",
    "companyName": "Kathir Kaman Project",
    "phone": "FB Messenger",
    "projectType": "Civil Construction",
    "location": "Tamil Nadu, India",
    "landArea": "10,000 sq ft",
    "estimatedBudget": 75,
    "timeline": "Immediate",
    "source": "Facebook Messenger",
    "assignedTo": "u1",
    "status": "New",
    "leadScore": 80,
    "notes": "Captured from FB Messenger. Message: \"Hi - Ad enquiry for PEB Building construction\"",
    "createdAt": "2026-07-17T16:59:00.000Z",
    "updatedAt": "2026-07-17T16:59:00.000Z"
  },
  {
    "id": "lead-fb-12",
    "contactName": "Manna Foods",
    "companyName": "Manna Foods",
    "phone": "FB Messenger",
    "projectType": "Other",
    "location": "Tamil Nadu, India",
    "landArea": "10,000 sq ft",
    "estimatedBudget": 80,
    "timeline": "Immediate",
    "source": "Facebook Messenger",
    "assignedTo": "u1",
    "status": "New",
    "leadScore": 80,
    "notes": "Captured from FB Messenger. Message: \"Hello - Cold storage & warehouse enquiry\"",
    "createdAt": "2026-07-18T04:11:00.000Z",
    "updatedAt": "2026-07-18T04:11:00.000Z"
  },
  {
    "id": "lead-fb-13",
    "contactName": "M Rahman",
    "companyName": "M Rahman Project",
    "phone": "FB Messenger",
    "projectType": "PEB Warehouse",
    "location": "Tamil Nadu, India",
    "landArea": "10,000 sq ft",
    "estimatedBudget": 85,
    "timeline": "Immediate",
    "source": "Facebook Messenger",
    "assignedTo": "u1",
    "status": "New",
    "leadScore": 80,
    "notes": "Captured from FB Messenger. Message: \"I'm rooftop sheet fitting working\"",
    "createdAt": "2026-07-11T17:42:00.000Z",
    "updatedAt": "2026-07-11T17:42:00.000Z"
  },
  {
    "id": "lead-fb-14",
    "contactName": "Nagallikar Manjunatha",
    "companyName": "Nagallikar Manjunatha Project",
    "phone": "FB Messenger",
    "projectType": "Cold Storage",
    "location": "Tamil Nadu, India",
    "landArea": "10,000 sq ft",
    "estimatedBudget": 90,
    "timeline": "Immediate",
    "source": "Facebook Messenger",
    "assignedTo": "u1",
    "status": "New",
    "leadScore": 80,
    "notes": "Captured from FB Messenger. Message: \"civil engineer\"",
    "createdAt": "2026-07-11T15:34:00.000Z",
    "updatedAt": "2026-07-11T15:34:00.000Z"
  }
];

export const sampleEnquiries: Enquiry[] = [
  {
    "id": "enq-fb-001",
    "contactName": "Ramya R",
    "phone": "FB Messenger",
    "lastMessage": "😍👑 STAR DESIGNER 👑😍😍 ...",
    "status": "New",
    "createdAt": "2026-07-22T10:21:00.000Z",
    "updatedAt": "2026-07-22T10:21:00.000Z"
  },
  {
    "id": "enq-fb-002",
    "contactName": "Rajesh Madasamy",
    "phone": "FB Messenger",
    "lastMessage": "Hey 👋",
    "status": "New",
    "createdAt": "2026-07-22T07:54:00.000Z",
    "updatedAt": "2026-07-22T07:54:00.000Z"
  },
  {
    "id": "enq-fb-003",
    "contactName": "Avj Architecture (Surya)",
    "phone": "FB Messenger",
    "lastMessage": "Hi sir🏡 I am AVJ PLANNER Surya 😆 We offer architectural planning and structural design.",
    "status": "New",
    "createdAt": "2026-07-20T14:30:00.000Z",
    "updatedAt": "2026-07-20T14:30:00.000Z"
  },
  {
    "id": "enq-fb-004",
    "contactName": "Tyagi Nikhil",
    "phone": "FB Messenger",
    "lastMessage": "Hlo",
    "status": "New",
    "createdAt": "2026-07-20T12:15:00.000Z",
    "updatedAt": "2026-07-20T12:15:00.000Z"
  },
  {
    "id": "enq-fb-005",
    "contactName": "Ravi Khede",
    "phone": "FB Messenger",
    "lastMessage": "Hello",
    "status": "New",
    "createdAt": "2026-07-20T11:00:00.000Z",
    "updatedAt": "2026-07-20T11:00:00.000Z"
  },
  {
    "id": "enq-fb-006",
    "contactName": "Raj Raj",
    "phone": "FB Messenger",
    "lastMessage": "Hi",
    "status": "New",
    "createdAt": "2026-07-17T18:20:00.000Z",
    "updatedAt": "2026-07-17T18:20:00.000Z"
  },
  {
    "id": "enq-fb-007",
    "contactName": "Barun Panigrahi",
    "phone": "FB Messenger",
    "lastMessage": "Messages and calls are secured with end-to-end encryption",
    "status": "New",
    "createdAt": "2026-07-17T17:45:00.000Z",
    "updatedAt": "2026-07-17T17:45:00.000Z"
  },
  {
    "id": "enq-fb-008",
    "contactName": "Kishan Patel Kishan Patel",
    "phone": "FB Messenger",
    "lastMessage": "Messages and calls are secured with end-to-end encryption",
    "status": "New",
    "createdAt": "2026-07-16T16:10:00.000Z",
    "updatedAt": "2026-07-16T16:10:00.000Z"
  },
  {
    "id": "enq-fb-009",
    "contactName": "Mugil",
    "phone": "FB Messenger",
    "lastMessage": "Hi - Interested in Pre-Engineered Building options",
    "status": "New",
    "createdAt": "2026-07-22T20:48:00.000Z",
    "updatedAt": "2026-07-22T20:48:00.000Z"
  },
  {
    "id": "enq-fb-010",
    "contactName": "Kartik Sethi",
    "phone": "FB Messenger",
    "lastMessage": "Hello - Call is not connecting please contact this number sir",
    "status": "New",
    "createdAt": "2026-07-17T17:00:00.000Z",
    "updatedAt": "2026-07-17T17:00:00.000Z"
  },
  {
    "id": "enq-fb-011",
    "contactName": "Kathir Kaman",
    "phone": "FB Messenger",
    "lastMessage": "Hi - Ad enquiry for PEB Building construction",
    "status": "New",
    "createdAt": "2026-07-17T16:59:00.000Z",
    "updatedAt": "2026-07-17T16:59:00.000Z"
  },
  {
    "id": "enq-fb-012",
    "contactName": "Manna Foods",
    "phone": "FB Messenger",
    "lastMessage": "Hello - Cold storage & warehouse enquiry",
    "status": "New",
    "createdAt": "2026-07-18T04:11:00.000Z",
    "updatedAt": "2026-07-18T04:11:00.000Z"
  },
  {
    "id": "enq-fb-013",
    "contactName": "M Rahman",
    "phone": "FB Messenger",
    "lastMessage": "I'm rooftop sheet fitting working",
    "status": "New",
    "createdAt": "2026-07-11T17:42:00.000Z",
    "updatedAt": "2026-07-11T17:42:00.000Z"
  },
  {
    "id": "enq-fb-014",
    "contactName": "Nagallikar Manjunatha",
    "phone": "FB Messenger",
    "lastMessage": "civil engineer",
    "status": "New",
    "createdAt": "2026-07-11T15:34:00.000Z",
    "updatedAt": "2026-07-11T15:34:00.000Z"
  }
];

export const sampleProjects: Project[] = [];
export const sampleFollowUps: FollowUp[] = [];
