import mongoose from 'mongoose';
import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';
import { Lead, connectDB } from '../backend/config/mongodb.js';

dotenv.config();

const realCompanyNames = ['Manna Foods', 'Avj Architecture', 'AVJ PLANNER'];

async function cleanCompanyNames() {
  await connectDB();
  console.log('Cleaning up auto-generated company names in MongoDB Atlas...');

  const leads = await Lead.find({});
  let cleanedCount = 0;

  for (const lead of leads) {
    const comp = (lead.companyName || '').trim();
    // If companyName ends with "Enterprise" or "Project" or equals contactName, check if it's a real company
    const isAutoGenerated = comp.endsWith('Enterprise') || 
                            comp.endsWith('Project') || 
                            comp === lead.contactName || 
                            comp === `${lead.contactName} Enterprise`;

    const isReal = realCompanyNames.some(rc => comp.toLowerCase().includes(rc.toLowerCase()) || lead.contactName.toLowerCase().includes(rc.toLowerCase()));

    if (isAutoGenerated && !isReal) {
      await Lead.updateOne({ _id: lead._id }, { companyName: '' });
      console.log(`- Cleared company for: ${lead.contactName} (was '${comp}')`);
      cleanedCount++;
    }
  }

  // Also clean db.json
  const dbPath = path.resolve('backend/db.json');
  if (fs.existsSync(dbPath)) {
    const dbData = JSON.parse(fs.readFileSync(dbPath, 'utf8'));
    if (dbData.leads && Array.isArray(dbData.leads)) {
      dbData.leads.forEach(l => {
        const comp = (l.companyName || '').trim();
        const isAutoGenerated = comp.endsWith('Enterprise') || comp.endsWith('Project') || comp === l.contactName;
        const isReal = realCompanyNames.some(rc => comp.toLowerCase().includes(rc.toLowerCase()) || (l.contactName && l.contactName.toLowerCase().includes(rc.toLowerCase())));

        if (isAutoGenerated && !isReal) {
          l.companyName = '';
        }
      });
      fs.writeFileSync(dbPath, JSON.stringify(dbData, null, 2));
      console.log('✅ Synchronized db.json file with cleaned company names!');
    }
  }

  console.log(`Successfully cleaned ${cleanedCount} auto-generated company names!`);
  process.exit(0);
}

cleanCompanyNames().catch(err => {
  console.error(err);
  process.exit(1);
});
